# This runs an ngrok container, so that I can tunnel webhooks through
# to the event listeners.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: policy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      name: ngrok
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: ngrok
      annotations:
        prometheus.io.port: "8080"
    spec:
      containers:
      - name: ngrok
        imagePullPolicy: IfNotPresent
        image: wernight/ngrok
        args:
        - ngrok
        - http
        - el-cuttlefacts-merge-listener.policy.svc.cluster.local:8080
        ports:
        - containerPort: 4040
          name: ngrok
