apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-triggers-webhook
    triggers.tekton.dev/release: v0.3.1
    version: v0.3.1
  name: tekton-triggers-webhook
  namespace: platform
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: tekton-triggers-webhook
