apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webhook-controller
    app.kubernetes.io/name: tekton-triggers
    triggers.tekton.dev/release: v0.3.1
  name: tekton-triggers-webhook
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-triggers-webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: tekton-triggers-webhook
        triggers.tekton.dev/release: v0.3.1
        version: v0.3.1
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook@sha256:7e3d8824ac60574de00a31c8afaba51fec33f7ca7b13e50d7dffea7c66e8b9eb
        name: webhook
        volumeMounts:
        - mountPath: /etc/config-logging
          name: config-logging
      serviceAccountName: tekton-triggers-controller
      volumes:
      - configMap:
          name: config-logging-triggers
        name: config-logging
