apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustertriggerbindings.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: ClusterTriggerBinding
    plural: clustertriggerbindings
    shortNames:
    - ctb
    singular: clustertriggerbinding
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
