apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    pipeline.tekton.dev/release: devel
  name: validation.webhook.pipeline.tekton.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: tekton-pipelines-webhook
      namespace: platform
  failurePolicy: Fail
  name: validation.webhook.pipeline.tekton.dev
  sideEffects: None
